const questionPaper = {
  title: 'SAMPLE QUESTION PAPER',
  class: 'Class X',
  session: 'Session 2024-25',
  subject: 'MATHEMATICS STANDARD',
  paperCode: 'Code No. 041',
  timeAllowed: '3 hours',
  maximumMarks: '100',
  generalInstructions: [
    'Read the following instructions carefully and follow them:',
    '1. All Questions are compulsory. However, an internal choice in 2 Question of Section B, 2 Questions of Section C and 2 Questions of Section D has been provided. An internal choice has been provided in all the 2 marks questions of Section E.',
    '2. Draw neat and clean figures wherever required.',
    '3. Take π = 22/7 wherever required if not stated.',
    '4. Use of calculators is not allowed.',
  ],
  sections: [
    {
      key: 'sectionA',
      title: 'Section A',
      instructions:
        'Questions 1-18 are multiple choice questions (MCQs) and questions 19-20 are Assertion-Reason based. Each question carries 1 mark.',
      marksPerQuestion: 1,
      questions: [
        // MCQs 1-18
        {
          id: 'q1',
          queNo: 1,
          queText: 'If the quadratic equation x² - 5x + 6 = 0 has roots α and β, then what is the value of α + β?',
          queType: 'MCQ',
          queMarks: 1,
          queImage: false,
          ansImage: false,
          queOptions: [
            { option1Text: '5', option1Image: false },
            { option2Text: '6', option2Image: false },
            { option3Text: '1', option3Image: false },
            { option4Text: '11', option4Image: false },
          ],
        },
        {
          id: 'q2',
          queNo: 2,
          queText: 'The value of sin 90° is:',
          queType: 'MCQ',
          queMarks: 1,
          queImage: false,
          ansImage: false,
          queOptions: [
            { option1Text: '0', option1Image: false },
            { option2Text: '1', option2Image: false },
            { option3Text: '-1', option3Image: false },
            { option4Text: '0.5', option4Image: false },
          ],
        },
        {
          id: 'q3',
          queNo: 3,
          queText: 'Which of the following is a rational number?',
          queType: 'MCQ',
          queMarks: 1,
          queImage: false,
          ansImage: false,
          queOptions: [
            { option1Text: '√2', option1Image: false },
            { option2Text: 'π', option2Image: false },
            { option3Text: '0.25', option3Image: false },
            { option4Text: 'e', option4Image: false },
          ],
        },
        {
          id: 'q4',
          queNo: 4,
          queText: 'The distance between the points (0,0) and (3,4) is:',
          queType: 'MCQ',
          queMarks: 1,
          queImage: false,
          ansImage: false,
          queOptions: [
            { option1Text: '5', option1Image: false },
            { option2Text: '7', option2Image: false },
            { option3Text: '1', option3Image: false },
            { option4Text: '4', option4Image: false },
          ],
        },
        {
          id: 'q5',
          queNo: 5,
          queText: 'The value of (a+b)² is:',
          queType: 'MCQ',
          queMarks: 1,
          queImage: false,
          ansImage: false,
          queOptions: [
            { option1Text: 'a² + b²', option1Image: false },
            { option2Text: 'a² + 2ab + b²', option2Image: false },
            { option3Text: 'a² - 2ab + b²', option3Image: false },
            { option4Text: 'a² + ab + b²', option4Image: false },
          ],
        },
        {
          id: 'q6',
          queNo: 6,
          queText: 'The HCF of 18 and 24 is:',
          queType: 'MCQ',
          queMarks: 1,
          queImage: false,
          ansImage: false,
          queOptions: [
            { option1Text: '6', option1Image: false },
            { option2Text: '12', option2Image: false },
            { option3Text: '18', option3Image: false },
            { option4Text: '24', option4Image: false },
          ],
        },
        {
          id: 'q7',
          queNo: 7,
          queText: 'The value of 2³ × 2² is:',
          queType: 'MCQ',
          queMarks: 1,
          queImage: false,
          ansImage: false,
          queOptions: [
            { option1Text: '4', option1Image: false },
            { option2Text: '8', option2Image: false },
            { option3Text: '16', option3Image: false },
            { option4Text: '32', option4Image: false },
          ],
        },
        {
          id: 'q8',
          queNo: 8,
          queText: 'The sum of the angles of a triangle is:',
          queType: 'MCQ',
          queMarks: 1,
          queImage: false,
          ansImage: false,
          queOptions: [
            { option1Text: '90°', option1Image: false },
            { option2Text: '180°', option2Image: false },
            { option3Text: '270°', option3Image: false },
            { option4Text: '360°', option4Image: false },
          ],
        },
        {
          id: 'q9',
          queNo: 9,
          queText: 'The area of a circle with radius r is:',
          queType: 'MCQ',
          queMarks: 1,
          queImage: false,
          ansImage: false,
          queOptions: [
            { option1Text: 'πr', option1Image: false },
            { option2Text: '2πr', option2Image: false },
            { option3Text: 'πr²', option3Image: false },
            { option4Text: 'πd', option4Image: false },
          ],
        },
        {
          id: 'q10',
          queNo: 10,
          queText: 'The value of 0 divided by any non-zero number is:',
          queType: 'MCQ',
          queMarks: 1,
          queImage: false,
          ansImage: false,
          queOptions: [
            { option1Text: '0', option1Image: false },
            { option2Text: '1', option2Image: false },
            { option3Text: 'Undefined', option3Image: false },
            { option4Text: 'Infinity', option4Image: false },
          ],
        },
        {
          id: 'q11',
          queNo: 11,
          queText: 'The solution of the equation 2x = 10 is:',
          queType: 'MCQ',
          queMarks: 1,
          queImage: false,
          ansImage: false,
          queOptions: [
            { option1Text: '2', option1Image: false },
            { option2Text: '5', option2Image: false },
            { option3Text: '10', option3Image: false },
            { option4Text: '20', option4Image: false },
          ],
        },
        {
          id: 'q12',
          queNo: 12,
          queText: 'The median of the data set 3, 5, 7 is:',
          queType: 'MCQ',
          queMarks: 1,
          queImage: false,
          ansImage: false,
          queOptions: [
            { option1Text: '3', option1Image: false },
            { option2Text: '5', option2Image: false },
            { option3Text: '7', option3Image: false },
            { option4Text: '6', option4Image: false },
          ],
        },
        {
          id: 'q13',
          queNo: 13,
          queText: 'The value of tan 45° is:',
          queType: 'MCQ',
          queMarks: 1,
          queImage: false,
          ansImage: false,
          queOptions: [
            { option1Text: '0', option1Image: false },
            { option2Text: '1', option2Image: false },
            { option3Text: '√3', option3Image: false },
            { option4Text: '2', option4Image: false },
          ],
        },
        {
          id: 'q14',
          queNo: 14,
          queText: 'The perimeter of a square of side 4 cm is:',
          queType: 'MCQ',
          queMarks: 1,
          queImage: false,
          ansImage: false,
          queOptions: [
            { option1Text: '8 cm', option1Image: false },
            { option2Text: '12 cm', option2Image: false },
            { option3Text: '16 cm', option3Image: false },
            { option4Text: '20 cm', option4Image: false },
          ],
        },
        {
          id: 'q15',
          queNo: 15,
          queText: 'The value of (–3)² is:',
          queType: 'MCQ',
          queMarks: 1,
          queImage: false,
          ansImage: false,
          queOptions: [
            { option1Text: '-9', option1Image: false },
            { option2Text: '9', option2Image: false },
            { option3Text: '6', option3Image: false },
            { option4Text: '0', option4Image: false },
          ],
        },
        {
          id: 'q16',
          queNo: 16,
          queText: 'The probability of getting a head when a coin is tossed once is:',
          queType: 'MCQ',
          queMarks: 1,
          queImage: false,
          ansImage: false,
          queOptions: [
            { option1Text: '0', option1Image: false },
            { option2Text: '0.5', option2Image: false },
            { option3Text: '1', option3Image: false },
            { option4Text: '2', option4Image: false },
          ],
        },
        {
          id: 'q17',
          queNo: 17,
          queText: 'The value of 5! (5 factorial) is:',
          queType: 'MCQ',
          queMarks: 1,
          queImage: false,
          ansImage: false,
          queOptions: [
            { option1Text: '120', option1Image: false },
            { option2Text: '60', option2Image: false },
            { option3Text: '24', option3Image: false },
            { option4Text: '20', option4Image: false },
          ],
        },
        {
          id: 'q18',
          queNo: 18,
          queText: 'The value of x if x + 7 = 12 is:',
          queType: 'MCQ',
          queMarks: 1,
          queImage: false,
          ansImage: false,
          queOptions: [
            { option1Text: '5', option1Image: false },
            { option2Text: '7', option2Image: false },
            { option3Text: '12', option3Image: false },
            { option4Text: '19', option4Image: false },
          ],
        },
        // Assertion-Reason 19-20
        {
          id: 'q19',
          queNo: 19,
          queText:
            'Assertion (A): The sum of the angles of a triangle is 180°.\nReason (R): A triangle can have two right angles.',
          queType: 'Assertion-Reason',
          queMarks: 1,
          queImage: false,
          ansImage: false,
          assertion: 'The sum of the angles of a triangle is 180°.',
          reason: 'A triangle can have two right angles.',
          queOptions: [
            {
              option1Text: 'Both Assertion and Reason are true and Reason is the correct explanation of Assertion',
              option1Image: false,
            },
            {
              option2Text: 'Both Assertion and Reason are true but Reason is not the correct explanation of Assertion',
              option2Image: false,
            },
            { option3Text: 'Assertion is true but Reason is false', option3Image: false },
            { option4Text: 'Assertion is false but Reason is true', option4Image: false },
          ],
        },
        {
          id: 'q20',
          queNo: 20,
          queText:
            'Assertion (A): The product of two odd numbers is always odd.\nReason (R): Odd numbers are not divisible by 2.',
          queType: 'Assertion-Reason',
          queMarks: 1,
          queImage: false,
          ansImage: false,
          assertion: 'The product of two odd numbers is always odd.',
          reason: 'Odd numbers are not divisible by 2.',
          queOptions: [
            {
              option1Text: 'Both Assertion and Reason are true and Reason is the correct explanation of Assertion',
              option1Image: false,
            },
            {
              option2Text: 'Both Assertion and Reason are true but Reason is not the correct explanation of Assertion',
              option2Image: false,
            },
            { option3Text: 'Assertion is true but Reason is false', option3Image: false },
            { option4Text: 'Assertion is false but Reason is true', option4Image: false },
          ],
        },
      ],
    },
    {
      key: 'sectionB',
      title: 'Section B',
      instructions:
        'Questions 21-25 are very short answer (VSA) type questions, carrying 2 marks each. Attempt all. Internal choice is provided in 2 questions.',
      marksPerQuestion: 2,
      questions: [
        {
          id: 'q21',
          queNo: 21,
          queText: 'Find the value of x if 3x + 5 = 20.',
          queType: 'Very Short Answer',
          queMarks: 2,
          queImage: false,
          ansImage: false,
        },
        {
          id: 'q22',
          queNo: 22,
          queText: 'Find the HCF of 36 and 48.',
          queType: 'Very Short Answer',
          queMarks: 2,
          queImage: false,
          ansImage: false,
          internalChoice: 'Find the LCM of 12 and 15.',
        },
        {
          id: 'q23',
          queNo: 23,
          queText: 'Write the value of (2/3) + (1/6).',
          queType: 'Very Short Answer',
          queMarks: 2,
          queImage: false,
          ansImage: false,
        },
        {
          id: 'q24',
          queNo: 24,
          queText: 'Find the area of a triangle with base 8 cm and height 5 cm.',
          queType: 'Very Short Answer',
          queMarks: 2,
          queImage: false,
          ansImage: false,
          internalChoice: 'Find the perimeter of a rectangle of length 7 cm and breadth 3 cm.',
        },
        {
          id: 'q25',
          queNo: 25,
          queText: 'If the mean of 5, 7, x, 13 is 10, find the value of x.',
          queType: 'Very Short Answer',
          queMarks: 2,
          queImage: false,
          ansImage: false,
        },
      ],
    },
    {
      key: 'sectionC',
      title: 'Section C',
      instructions:
        'Questions 26-31 are short answer (SA) type questions, carrying 3 marks each. Attempt all. Internal choice is provided in 2 questions.',
      marksPerQuestion: 3,
      questions: [
        {
          id: 'q26',
          queNo: 26,
          queText: 'Solve for x: 2x² - 8x + 6 = 0.',
          queType: 'Short Answer',
          queMarks: 3,
          queImage: false,
          ansImage: false,
        },
        {
          id: 'q27',
          queNo: 27,
          queText: 'Find the value of k if the lines 2x + 3y = 7 and 4x + ky = 14 are parallel.',
          queType: 'Short Answer',
          queMarks: 3,
          queImage: false,
          ansImage: false,
        },
        {
          id: 'q28',
          queNo: 28,
          queText: 'Find the area of a circle whose circumference is 44 cm.',
          queType: 'Short Answer',
          queMarks: 3,
          queImage: false,
          ansImage: false,
          internalChoice: 'Find the circumference of a circle whose area is 154 cm².',
        },
        {
          id: 'q29',
          queNo: 29,
          queText: 'If the roots of the equation x² + px + 12 = 0 are -3 and -4, find the value of p.',
          queType: 'Short Answer',
          queMarks: 3,
          queImage: false,
          ansImage: false,
        },
        {
          id: 'q30',
          queNo: 30,
          queText: 'Find the mode of the following data: 2, 3, 3, 5, 7, 3, 8.',
          queType: 'Short Answer',
          queMarks: 3,
          queImage: false,
          ansImage: false,
          internalChoice: 'Find the median of the following data: 4, 7, 9, 10, 12.',
        },
        {
          id: 'q31',
          queNo: 31,
          queText:
            'A school is organizing a stair climbing challenge for its students. The first student climbs 1 step, the second climbs 2 steps, the third climbs 3 steps, and so on, with each subsequent student climbing one more step than the previous student. If the total number of steps climbed by all students together is 210, how many students participated in the challenge? Show all steps clearly, including the formula used for the sum of the first n natural numbers, and verify your answer.',
          queType: 'Short Answer',
          queMarks: 3,
          queImage: false,
          ansImage: false,
        },
      ],
    },
    {
      key: 'sectionD',
      title: 'Section D',
      instructions:
        'Questions 32-35 are long answer (LA) type questions, carrying 5 marks each. Attempt all. Internal choice is provided in 2 questions.',
      marksPerQuestion: 5,
      questions: [
        {
          id: 'q32',
          queNo: 32,
          queText: 'Prove that the sum of the squares of any two odd numbers is always even.',
          queType: 'Long Answer',
          queMarks: 5,
          queImage: false,
          ansImage: false,
        },
        {
          id: 'q33',
          queNo: 33,
          queText: 'Find the roots of the equation x² - 4x + 3 = 0 by factorization method.',
          queType: 'Long Answer',
          queMarks: 5,
          queImage: false,
          ansImage: false,
          internalChoice: 'Solve the equation x² - 5x + 6 = 0 by quadratic formula.',
        },
        {
          id: 'q34',
          queNo: 34,
          queText:
            'A train travels 150 km at a speed of 50 km/h and returns at a speed of 30 km/h. Find the average speed of the train for the whole journey.',
          queType: 'Long Answer',
          queMarks: 5,
          queImage: false,
          ansImage: false,
        },
        {
          id: 'q35',
          queNo: 35,
          queText: 'Prove that √3 is an irrational number.',
          queType: 'Long Answer',
          queMarks: 5,
          queImage: false,
          ansImage: false,
          internalChoice: 'Prove that √2 is an irrational number.',
        },
      ],
    },
    {
      key: 'sectionE',
      title: 'Section E',
      instructions:
        'Questions 36-38 are case study based questions carrying 4 marks each with sub parts of the values of 1, 1 and 2 marks each respectively. Internal choice is provided in all 2 marks questions.',
      marksPerQuestion: 4,
      questions: [
        {
          id: 'q36',
          queNo: 36,
          queText:
            'A rectangular garden is 20 m long and 15 m wide. A path of width 1 m is constructed inside and along the boundary of the garden. Answer the following:',
          queType: 'Case Study',
          queMarks: 4,
          queImage: false,
          ansImage: false,
          subParts: [
            {
              subId: 'q36a',
              queNo: '36a',
              queText: 'What is the area of the garden before the path is constructed?',
              queMarks: 1,
              queImage: false,
              ansImage: false,
            },
            {
              subId: 'q36b',
              queNo: '36b',
              queText: 'What are the dimensions of the garden after the path is constructed?',
              queMarks: 1,
              queImage: false,
              ansImage: false,
            },
            {
              subId: 'q36c',
              queNo: '36c',
              queText: 'Find the area of the path.',
              queMarks: 2,
              queImage: false,
              ansImage: false,
              internalChoice: 'Find the cost of constructing the path at the rate of ₹50 per m².',
            },
          ],
        },
        {
          id: 'q37',
          queNo: 37,
          queText:
            'A box contains 3 red balls, 5 green balls, and 2 blue balls. A ball is drawn at random. Answer the following:',
          queType: 'Case Study',
          queMarks: 4,
          queImage: false,
          ansImage: false,
          subParts: [
            {
              subId: 'q37a',
              queNo: '37a',
              queText: 'What is the total number of balls in the box?',
              queMarks: 1,
              queImage: false,
              ansImage: false,
            },
            {
              subId: 'q37b',
              queNo: '37b',
              queText: 'What is the probability of drawing a green ball?',
              queMarks: 1,
              queImage: false,
              ansImage: false,
            },
            {
              subId: 'q37c',
              queNo: '37c',
              queText: 'What is the probability of drawing either a red or a blue ball?',
              queMarks: 2,
              queImage: false,
              ansImage: false,
              internalChoice: 'What is the probability of not drawing a green ball?',
            },
          ],
        },
        {
          id: 'q38',
          queNo: 38,
          queText: 'A right circular cylinder has a height of 10 cm and a base radius of 7 cm. Answer the following:',
          queType: 'Case Study',
          queMarks: 4,
          queImage: false,
          ansImage: false,
          subParts: [
            {
              subId: 'q38a',
              queNo: '38a',
              queText: 'Find the volume of the cylinder.',
              queMarks: 1,
              queImage: false,
              ansImage: false,
            },
            {
              subId: 'q38b',
              queNo: '38b',
              queText: 'Find the curved surface area of the cylinder.',
              queMarks: 1,
              queImage: false,
              ansImage: false,
            },
            {
              subId: 'q38c',
              queNo: '38c',
              queText: 'Find the total surface area of the cylinder.',
              queMarks: 2,
              queImage: false,
              ansImage: false,
              internalChoice: 'If the height is doubled, what will be the new volume of the cylinder?',
            },
          ],
        },
      ],
    },
  ],
};

export default questionPaper;
